### ISSUE TITLE
PHP version problems with composer

### ISSUE THREAD

**Issue by Maumtrasna** [Part-DB/Part-DB#101]
Has anybody used  any newer versions of PHP or sorted out the problems with PHP8? 

`  Problem 1

    - Installation request for smarty-gettext/smarty-gettext 1.5.1 -> satisfiable by smarty-gettext/smarty-gettext[1.5.1].
    - smarty-gettext/smarty-gettext 1.5.1 requires php ~5.3|~7.0 -> your PHP version (8.0.13) does not satisfy that requirement.
    
  Problem 2

    - Installation request for filp/whoops 2.4.1 -> satisfiable by filp/whoops[2.4.1].
    - filp/whoops 2.4.1 requires php ^5.5.9 || ^7.0 -> your PHP version (8.0.13) does not satisfy that requirement.

  Problem 3

    - Installation request for symfony/var-dumper v4.3.2 -> satisfiable by symfony/var-dumper[v4.3.2].
    - symfony/var-dumper v4.3.2 requires php ^7.1.3 -> your PHP version (8.0.13) does not satisfy that requirement.
 
 Problem 4

    - symfony/var-dumper v4.3.2 requires php ^7.1.3 -> your PHP version (8.0.13) does not satisfy that requirement.
    - maximebf/debugbar v1.15.0 requires symfony/var-dumper ^2.6|^3.0|^4.0 -> satisfiable by symfony/var-dumper[v4.3.2].
    - Installation request for maximebf/debugbar v1.15.0 -> satisfiable by maximebf/debugbar[v1.15.0].
`

**Comment by jbtronics** [comment]
This is now fixed in 0.5.10 and the latest master commits
