### ISSUE TITLE
Error calling [/de/](http://myip/de/).

### ISSUE THREAD

**Issue by pixbalance** [Part-DB/Part-DB#121]
Since I ran the update I can login but then I get the follwing error message

Internal Server Error (Status 500)

Error calling [/de/](http://myip/de/).
Try to reload the page or contact the administrator if this error persists.

When I change the language to en, it says Error calling [/en/](http://myip/de/).

When I try to open parts it says: Error calling [/en/category/5/parts](http://172.16.0.77/en/category/5/parts).

I did not change anything else on the system or the database/location.

**Comment by jbtronics** [comment]
Assuming that you have upgraded to Part-DB 1.*, this is the wrong repository. Open the ticket here: https://github.com/Part-DB/Part-DB-server

Have you upgraded/migrated the database schema after software Update?
