### ISSUE TITLE
Feature: docker image? 

### ISSUE THREAD

**Issue by terxw** [Part-DB/Part-DB#14]
Would it be possible to include docker configuration/age for this software which would automate and separete server onstallation

**Comment by jbtronics** [comment]
I had this idea already too xD
I not so experienced with docker, but I will see what I can do the next days.

**Comment by jbtronics** [comment]
With schulzh's PR we now support docker. I've created an image on Docker Hub (jbtronics/part-db) which is automatically synced with this Repo.

Under https://github.com/Part-DB/Part-DB-docker docker-compose files can be found which setup a complete running instance of Part-DB including database.
