### ISSUE TITLE
"nextgen.zip" nicht mehr verfügbar?

### ISSUE THREAD

**Issue by jlegen** [Part-DB/Part-DB#30]
Abruf von https://codeload.github.com/Part-DB/Part-DB/zip/nextgen resultiert in "404 not found"...

**Comment by jbtronics** [comment]
Ich habe den nextgen-Branch umbenannt zu master, um der Benennung zu folgen wie sie eigentlich üblich ist.

Wenn du in dem Link nextgen durch master ersetzt, dann erhältst du die Datei von früher...

Steht dieser Link irgendwo in Part-DB oder der Dokumentation, denn dann würde ich das ändern, damit keine Verwirrung auftaucht

**Comment by jlegen** [comment]
Yep, hier im Wiki unter "Download and unpack Part-DB"...

**Comment by jbtronics** [comment]
Hab es geändert
