### ISSUE TITLE
Can't delete an attachment

### ISSUE THREAD

**Issue by marklinmax** [Part-DB/Part-DB#59]
I just successfully installed part-DB and started filling it with my components. I wanted to delete an attachment to a part, but nothing happen when I click on the button, and I get this error on the EventLog:
Error:Call to protected PartDB\Part::__construct() from context 'PartDB\Attachment' [/var/www/html/partdb/Part-DB-master/lib/Attachment.php, 219]

I am using Part-DB 0.6.0-dev, running with php7.0.33 and mysql

**Comment by jbtronics** [comment]
Should be fixed now, with the latest commit.
