### ISSUE TITLE
Cost Calculations

### ISSUE THREAD

**Issue by a7hybnj2** [Part-DB/Part-DB#75]
It doesn't appear that the quantity breaks are being calculated correctly. When for instance you have a device that uses 10 parts and you make 1 device by clicking remove 1 button.

If you then go to the history of that part the costs displayed at the far right don't follow the quantity breaks.

**Comment by jbtronics** [comment]
Same as in issue #74, I think that would need some deeper changes in the way orders and prices are handled, so I won't fix that in this repo.
