### ISSUE TITLE
Verbesserungen / Bug Report

### ISSUE THREAD

**Issue by cAbtHelectronics** [Part-DB/Part-DB#78]
Hallo,
ich benutze jetzt PartDB schon eine weile, und mir sind erstmal folgende Dinge aufgefallen:
- Wenn man einen Benutzer löscht, der einmal einen Artikel bearbeitet oder einen Artikel abgefasst hat, ist dieser Artikel nicht mehr aufzurufen, da der User in der Historie fehlt. Man muss ihn ja nicht komplett löschen, aber zum Beispiel als inaktiv setzten wäre schon ziemlich hilfreich.
- Wenn man Artikel über die Suchleiste sucht, findet die Suchfunktion ab einer gewissen Zeichenlänge keine Artikel mehr.

Außerdem hab ich noch ein paar Anregungen für Funktionen, die mir in diesem Programm so etwas fehlen:
- [ ] es gibt für Artikel nur Stückzahlen, weitere Maßeinheiten wie Länge oder Gewicht wären gut.

- [ ] Baugruppen Werte bzw. Stückzahlen zuordnen. Wenn ich eine Baugruppe abfasse, wäre es gut, wenn diese Baugruppe, dann auch in der Datenbank als Artikel auftaucht. Momentan muss man eine Baugruppe abfassen und dann bei einem erstellten Artikel die gebaute Baugruppe hinzufügen.

- [ ] wir haben momentan es so gelöst das eine Baugruppe aus verschiedenen Baugruppen besteht. Daher wäre es zum Vorteil, wenn man zum Beispiel die oberste Baugruppe abfassen kann und dadurch direkt die Unterbaugruppen abfassen kann.

Wäre schön wenn ein paar von den oben genannten Punkten übernommen werden. Von mir aus auch in Funktionen in Symfony.

**Comment by jbtronics** [comment]
Das meiste davon ist bereits in der symfony-basierenden Version (https://github.com/Part-DB/Part-DB-symfony) implementiert, bzw. sollte behoben sein. Dort kann man auch beliebige Maßeinheiten für Bauteile definieren und verwenden.

Die Baugruppenfunktion muss eh komplett überarbeitet werden, im aktuellen Zustand finde ich sie nicht wirklich hilfreich. Das wird dann aber in der Symfony-Version geschehen (wo es momentan noch gar keine Baugruppenfunktion gibt).
