### ISSUE TITLE
Bug: Type Error on spuuplier link on part page

### ISSUE THREAD

**Issue by rs-development** [Part-DB/Part-DB#79]
I am running PartDB from your provided docker container. See below. I get the following error after clicking on Supplier Link on the procut page.

Where should this link leed?
Whats the intention of the SELECT?

I take i closer look at it later today, let me know if you need more information!

![image](https://user-images.githubusercontent.com/35149229/79597680-0222fb80-80e3-11ea-8262-056fdadbaf4f.png)
Corresponding php code:

![image](https://user-images.githubusercontent.com/35149229/79597759-1ff06080-80e3-11ea-9168-4721ea15c94b.png)

Database entries:

![image](https://user-images.githubusercontent.com/35149229/79597813-3c8c9880-80e3-11ea-9298-2583ff44b399.png)

![image](https://user-images.githubusercontent.com/35149229/79597984-7a89bc80-80e3-11ea-91cc-b07406cae96d.png)

Actual Container used:

{
        "Id": "sha256:f5c33f6201e0145c1c802b69496fc3d16f3d8c46cb56ee3cac52b7e80df200cd",
        "RepoTags": [
            "jbtronics/part-db:latest"
        ],
        "RepoDigests": [
            "jbtronics/part-db@sha256:7a07b1904b180040004365e8a45d5e2ee099a66c028683ed732a37338ebfc497"
        ],

**Comment by rs-development** [comment]
![image](https://user-images.githubusercontent.com/35149229/79598996-1962e880-80e5-11ea-9eae-122134fae5fd.png)

So the query itself seems to be working IF the supplier ID is given correctly.

**Comment by rs-development** [comment]
A simple cast to int fixed the error. But why the cast is needed in my case?

**Comment by jbtronics** [comment]
As it is not possible for PDO know which type was returned by DB, it returns the value as string.
But as the getPartsCount() function must return an int, it fails, when trying to return some other type (like string).

This is an leftover from the 0.5.* versions (there was no return typehint, so the DB value was converted to int implicitly somewhere else). All other Elements use another base method, which already included the int cast: https://github.com/Part-DB/Part-DB/blob/0c9fa13fa697385a2db6cfbc4e814f8a03dcd0de/lib/Base/PartsContainingDBElement.php#L287

This kind of problems hopefully does not happen so often in the new Part-DB 1.0 versions, as it is developed with strict typing in mind and Doctrine does most of low level database things...

**Comment by rs-development** [comment]
Thanks for the fast response! I was in doubt whether I messed up the database or not.
