### ISSUE TITLE
add landing page text

### ISSUE THREAD

**Issue by manuel-91** [Part-DB/Part-DB#80]
Is there a way to add/modify the text that is printed when I go to the landing page?

At the moment the [landing page of the demo](http://part-db.bplaced.net/part-en/startup.php) shows:
- name of the instance, current version, user login
- licence informations

It would be great if (maybe in settings) an additional text here could be edited. The text could explain things like:
- who is the maintainer of the service technically
- who maintains the db content?
- when location of a part tells "box42" or "locker404", where are they in a few more words. Whom to ask? Maybe a link to an internal wiki.
- how to buy more parts, is it done monthly, who is doing that

**Comment by jbtronics** [comment]
In settings there is the possibility for some BBCode that is shown on the start page.
You can use that add custom text and links to your start page.

**Comment by manuel-91** [comment]
Thank you very much!
